title: Триада Тела
description: Выездной массаж по личной технике Триада. Абакан, Кызыл, Красноярск.
author: Мастер Триады
telegram_username: rus878
telegram_url: https://t.me/rus878
google_sheets_id: 1xi7pi8q7j5E2orNAesWivw-9Wj-bzjtrB5_hSCJPzXI
url: https://triada-touch.ru
baseurl: ""
markdown: kramdown
